// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC201yxoq39jsthO_T0lIF0H8R61yKY7MM',
    appId: '1:826736396563:web:5d14cff9c7803a590672e6',
    messagingSenderId: '826736396563',
    projectId: 'smartboxingenergy-b5cdf',
    authDomain: 'smartboxingenergy-b5cdf.firebaseapp.com',
    storageBucket: 'smartboxingenergy-b5cdf.firebasestorage.app',
    measurementId: 'G-03E87Z8LG0',
  );

  static const FirebaseOptions android = FirebaseOptions(

    apiKey: 'AIzaSyChD1HjbVuNfEwiXx9bSDzoCyaKyJ82gEA',
    appId: '1:826736396563:android:313f114398d9fe7b0672e6',
    messagingSenderId: '826736396563',
    projectId: 'smartboxingenergy-b5cdf',
    storageBucket: 'smartboxingenergy-b5cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRYqYoTTULwAKBWVeOjOYY2kxbFYStHU',
    appId: '1:826736396563:ios:f4aa50a9d5ca01bf0672e6',
    messagingSenderId: '826736396563',
    projectId: 'smartboxingenergy-b5cdf',
    storageBucket: 'smartboxingenergy-b5cdf.firebasestorage.app',
    iosBundleId: 'com.example.projects.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRYqYoTTULwAKBWVeOjOYY2kxbFYStHU',
    appId: '1:826736396563:ios:f4aa50a9d5ca01bf0672e6',
    messagingSenderId: '826736396563',
    projectId: 'smartboxingenergy-b5cdf',
    storageBucket: 'smartboxingenergy-b5cdf.firebasestorage.app',
    iosBundleId: 'com.example.projects.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC201yxoq39jsthO_T0lIF0H8R61yKY7MM',
    appId: '1:826736396563:web:4bed0e3af8d4d0c90672e6',
    messagingSenderId: '826736396563',
    projectId: 'smartboxingenergy-b5cdf',
    authDomain: 'smartboxingenergy-b5cdf.firebaseapp.com',
    storageBucket: 'smartboxingenergy-b5cdf.firebasestorage.app',
    measurementId: 'G-1MDL7C3H7X',
  );
}
